<?php
$picname=$_FILES['pic']['name'];
$picsize=$_FILES['pic']['size'];
$service=$_POST['service'];
$aa=json_decode(html_entity_decode('[{&quot;setting_id_model&quot;:&quot;50&quot;,&quot;hrebs_name&quot;:&quot;苍果&quot;,&quot;id&quot;:&quot;2&quot;,&quot;drug_num&quot;:&quot;100&quot;}]'));
foreach($aa as $row)
{
	print_r($row['setting_id_model']);
}
if($picname!="")
{
	include_once("./Core/Library/Vendor/vendor/autoload.php");
	$oss=new \OSS\OssClient('LTAIbcaJ17DMTSFr','XKR5IlIYBP8cETMHhFHQwsEpCuYowL','http://sxgzzyy.oss-cn-shanghai.aliyuncs.com',true);
	if($picsize>4096000)
	{
		$arr['error']=1;
		$arr['error_msg']='图片大小不能超过4M！';
	}
	else
	{
		$type=strtolower(strstr($picname,'.'));
		if ($type!=".png"&&$type!=".jpg"&&$type!=".jpeg")
		{
			$arr['error']=0;
			$arr['error_msg']='只支持png和jpg两种格式！';
		}
		else
		{
			
			$rand=rand(1000,9999);
			$filename=time().$rand;
			if($service=='oss')
			{
			$pic_path="oss/".date("Y-m-d")."/".$filename.$type;
			$oss->uploadfile('sxgzzyy',$pic_path,$_FILES['pic']['tmp_name']);
			}
			else
			{
				$dir="./Uploads/oss/".date("Y-m-d")."/";				
				if(!is_dir($dir))
				{
					mkdir($dir,0777);
				}
				$pics=$filename.$type;
				//上传路径
				$pic_path=$dir.$pics;
				if(move_uploaded_file($_FILES['pic']['tmp_name'],$pic_path))
				{
					$pic_path=$pic_path;
				}
				else
				{
					$arr['error']=0;
					$arr['error_msg']='上传失败！';
				}
			}
		}
	}
}
else
{
	$arr['error']=0;
	$arr['error_msg']='请选择上传文件！';
}
$arr['pic']=$pic_path;
$arr['filename']=$filename;
die(json_encode($arr));
?>